In [6]:
# Loading the dataset 
import pandas as pd

file_name = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_name, encoding='latin-1')
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [7]:
#To check the regions in the dataset
df['estado'].unique()

array(['Acre', 'alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
       'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
       'Mato Grosso', 'Minas Gerais', 'pará', 'Paraiba', 'Pernambuco',
       'Piau', 'Rio', 'rondonia', 'Roraima', 'Santa Catarina',
       'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object)

# Renaming the columns to English

In [9]:
new_columns_names = {
    'ano' : 'year',
    'mes' : 'month',
    'estado' : 'state',
    'numero': 'number_of_fires',
    'encontro': 'date'
}
df.rename(columns = new_columns_names, inplace = True)

In [10]:
df.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre         0 Fires  1/1/1998
1  1999  Janeiro  Acre         0 Fires  1/1/1999
2  2000  Janeiro  Acre         0 Fires  1/1/2000
3  2001  Janeiro  Acre         0 Fires  1/1/2001
4  2002  Janeiro  Acre         0 Fires  1/1/2002

In [11]:
df['year'].unique()

array([1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017], dtype=int64)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             5 non-null      int64
 1   month            5 non-null      object
 2   state            5 non-null      object
 3   number_of_fires  5 non-null      object
 4   date             5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

# Rearranging the columns

In [18]:
# reordering the columns accordingly
new_order = [4,1,0,2,3]
df = df[df.columns[new_order]]
df.head()

       date    month  year state number_of_fires
0  1/1/1998  Janeiro  1998  Acre         0 Fires
1  1/1/1999  Janeiro  1999  Acre         0 Fires
2  1/1/2000  Janeiro  2000  Acre         0 Fires
3  1/1/2001  Janeiro  2001  Acre         0 Fires
4  1/1/2002  Janeiro  2002  Acre         0 Fires

# Determining if a column contains numeric data

In [19]:
# it isn't, let's find our why
df['number_of_fires'].str.isnumeric()

0    False
1    False
2    False
3    False
4    False
Name: number_of_fires, dtype: bool

In [22]:
df['number_of_fires'].astype(str).str.isdigit()

0    False
1    False
2    False
3    False
4    False
Name: number_of_fires, dtype: bool

# Removing the unecessay text from the columns

In [24]:
# using strip to remove the spaces and then checking if the values are numeric
df['number_of_fires'].str.strip("Fires")

0    0
1    0
2    0
3    0
4    0
Name: number_of_fires, dtype: object

In [25]:
# Replacing the column with the cleaned column
df['number_of_fires'] = df['number_of_fires'].str.strip("Fires").astype(int)
df.head()

       date    month  year state  number_of_fires
0  1/1/1998  Janeiro  1998  Acre                0
1  1/1/1999  Janeiro  1999  Acre                0
2  1/1/2000  Janeiro  2000  Acre                0
3  1/1/2001  Janeiro  2001  Acre                0
4  1/1/2002  Janeiro  2002  Acre                0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             5 non-null      object
 1   month            5 non-null      object
 2   year             5 non-null      int64
 3   state            5 non-null      object
 4   number_of_fires  5 non-null      int32
dtypes: int32(1), int64(1), object(3)
memory usage: 312.0+ bytes

In [29]:
# conveting the number of fires to a float data type and also this is the alternative string manipulation method to remove the "Fires" string from the column
# df["number_of_fires"] = df["number_of_fires"].str.replace("", "0").astype(float)
# df.head()
print(df["number_of_fires"].dtype)
print(df["number_of_fires"].head())

int32
0    0
1    0
2    0
3    0
4    0
Name: number_of_fires, dtype: int32

In [30]:
# If it's already numeric — just convert directly, no str needed
df["number_of_fires"] = df["number_of_fires"].astype(float)

# If it's mixed (some strings, some numbers) — convert safely
df["number_of_fires"] = pd.to_numeric(df["number_of_fires"], errors='coerce').fillna(0)

In [31]:
df.head()

       date    month  year state  number_of_fires
0  1/1/1998  Janeiro  1998  Acre              0.0
1  1/1/1999  Janeiro  1999  Acre              0.0
2  1/1/2000  Janeiro  2000  Acre              0.0
3  1/1/2001  Janeiro  2001  Acre              0.0
4  1/1/2002  Janeiro  2002  Acre              0.0

# Handelling the missing values

In [ ]:
# reloding the dataset
file_naam = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_naam, encoding='latin-1')
naya_columns = {
    'ano' : 'year',
    'mes' : 'month',
    'estado' : 'state',
    'numero': 'number_of_fires',
    'encontro': 'date'
}
df.rename(columns = naya_columns, inplace = True)
df['number_of_fires'] = df['number_of_fires'].str.strip("Fires")
#creating a true copy of the dataset
df_copy = df.copy()
df_copy.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [34]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             6454 non-null   int64
 1   month            6454 non-null   object
 2   state            6454 non-null   object
 3   number_of_fires  6322 non-null   object
 4   date             6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [35]:
df_copy.isnull().sum()

year                 0
month                0
state                0
number_of_fires    132
date                 0
dtype: int64

In [38]:
#  we easily remove the NUll or Nan (not a number) values from the dataset using the dropna() method    
df_copy.dropna(inplace = True)
df_copy.reset_index()
df_copy.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [39]:
df_copy.isnull().sum()

year               0
month              0
state              0
number_of_fires    0
date               0
dtype: int64

# Other MEthods of handelling missing values

In [42]:
# reloding the dataset to check if the changes are permanent
file_naam = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_naam, encoding='latin-1')    
new_columns_names = {
    'ano' : 'year',
    'mes' : 'month', 
    'estado' : 'state',
    'numero': 'number_of_fires',    
    'encontro': 'date'
}
df.rename(columns = new_columns_names, inplace = True)

df['number_of_fires'] = df['number_of_fires'].str.strip("Fires")
df_kapy = df.copy()
df.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [43]:
df.isnull().sum()

year                 0
month                0
state                0
number_of_fires    132
date                 0
dtype: int64

In [48]:
df[df['number_of_fires'].isnull()].head ()

     year     month state number_of_fires      date
68   2006     Abril  Acre             NaN  1/1/2006
110  2008     Junho  Acre             NaN  1/1/2008
127  2005     Julho  Acre             NaN  1/1/2005
206  2004  Novembro  Acre             NaN  1/1/2004
217  2015  Novembro  Acre             NaN  1/1/2015

##### what to do with the missing data? 
1. remove them using dropn(axis = 0 )
2 . replace them with some arbitary number (e.g. an average)
3 . replace them zeros , or forward fill method or backward fill

In [64]:
#using fillna with zeros
df = df_kapy
df['number_of_fires'] = df['number_of_fires'].fillna(0)
df.head(70)

    year    month state number_of_fires      date
0   1998  Janeiro  Acre              0   1/1/1998
1   1999  Janeiro  Acre              0   1/1/1999
2   2000  Janeiro  Acre              0   1/1/2000
3   2001  Janeiro  Acre              0   1/1/2001
4   2002  Janeiro  Acre              0   1/1/2002
..   ...      ...   ...             ...       ...
65  2003    Abril  Acre              1   1/1/2003
66  2004    Abril  Acre              2   1/1/2004
67  2005    Abril  Acre              1   1/1/2005
68  2006    Abril  Acre               0  1/1/2006
69  2007    Abril  Acre              0   1/1/2007

[70 rows x 5 columns]

In [60]:
# lets try with the filling 
df['number_of_fires'] = df['number_of_fires'].fillna(method = 'ffill')
df.head(70)

C:\Users\Acer\AppData\Local\Temp\ipykernel_12692\2943543932.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['number_of_fires'] = df['number_of_fires'].fillna(method = 'ffill')

    year    month state number_of_fires      date
0   1998  Janeiro  Acre              0   1/1/1998
1   1999  Janeiro  Acre              0   1/1/1999
2   2000  Janeiro  Acre              0   1/1/2000
3   2001  Janeiro  Acre              0   1/1/2001
4   2002  Janeiro  Acre              0   1/1/2002
..   ...      ...   ...             ...       ...
65  2003    Abril  Acre              1   1/1/2003
66  2004    Abril  Acre              2   1/1/2004
67  2005    Abril  Acre              1   1/1/2005
68  2006    Abril  Acre              1   1/1/2006
69  2007    Abril  Acre              1   1/1/2007

[70 rows x 5 columns]

In [58]:
# view index 444 to see how it changes
df.iloc[444]

year                   2002
month              Novembro
state               alagoas
number_of_fires          1
date               1/1/2002
Name: 444, dtype: object